export const CODE = {
    ERROR: 'ERROR',
    EMAIL_EXISTED : 'EMAIL_EXISTED',
    INVALID: 'INVALID',
    WRONG_CREDENTIAL : 'WRONG_CREDENTIAL',
    DONE: 'DONE',
    NOT_LOGIN: 'NOT_LOGIN',
    NOT_ACTIVE: 'NOT_ACTIVE'
}
